### ISSUE TITLE
Framework not found WebP

### ISSUE THREAD

**Issue by mauriciogtaborda** [Jobeso/react-native-whatsapp-stickers#16]
## Environment
Environment:
 OS: macOS High Sierra 10.13.6
 Node: 8.5.0
 Yarn: 1.7.0
 npm: 6.4.1
 Watchman: 4.7.0
 Xcode: Xcode 9.4.1 Build version 9F2000

i completed the installation and integration described in the docs but when i run my project shows this error.

ld: warning: directory not found for option '-L/Users/***/Library/Developer/Xcode/DerivedData/****-ayyjwebyaveiesgkcsfanqobqvie/Build/Products/Debug-iphoneos/React'
ld: framework not found WebP
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Jobeso** [comment]
This usually means that the linking of the framework was not correctly done. See [this](https://github.com/Jobeso/react-native-whatsapp-stickers#integrate-webp-framework) section for instructions on how to add the WebP framework. I suggest you to start of again if you did some of these steps. The linking process with react-native is always difficult.

**Comment by mauriciogtaborda** [comment]
> This usually means that the linking of the framework was not correctly done. See [this](https://github.com/Jobeso/react-native-whatsapp-stickers#integrate-webp-framework) section for instructions on how to add the WebP framework. I suggest you to start of again if you did some of these steps. The linking process with react-native is always difficult.

i link the webP framework correctly again and i got the same error.

**Comment by kkleeez** [comment]
I have the same problem and resolve it by adding 
"$(SRCROOT)/../node_modules/react-native-whatsapp-stickers/ios"
in "Framework Search Paths" in Project Building Settings page

**Comment by pandanr1** [comment]
Same here. kkleeez solution does not help :/

`
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 1.69 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
`

**Comment by kkleeez** [comment]
Hi pandanr1, I forgot to mention in my solution. You need to set the search path to "recursive".

**Comment by pandanr1** [comment]
Works thank you so much kkleez!

**Comment by Jobeso** [comment]
Closing this for now, seems like it solved your problem.

If you are having the same issue, try the solution of @kkleeez in https://github.com/Jobeso/react-native-whatsapp-stickers/issues/16#issuecomment-468883862 and https://github.com/Jobeso/react-native-whatsapp-stickers/issues/16#issuecomment-474684449.
