### ISSUE TITLE
whatsapp.send is undefined

### ISSUE THREAD

**Issue by creeptosis** [Jobeso/react-native-whatsapp-stickers#17]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 54.16 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.1, 28.0.3
        System Images: android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.56.1 => 0.56.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
Hi, I follow the integration steps exactly for both platforms and finally got the project to build. I think the module should be linked correctly caused I ran into a lot of errors regarding RNWhatsappStickers along the way, such as minSdkVersion, couldnt resolve dependencies, etc etc.. for some reason on both IOS & Android the only method I can use is isWhatsAppAvailable. .send .createStickerPack is all undefined

**Comment by Jobeso** [comment]
Did you find some time to debug this further? 
It might be a linking problem with the native files. `isWhatsAppAvailable` is a JS only function but the other ones are exported from native.

**Comment by creeptosis** [comment]
Hi @Jobeso , I knew that the problem was with linking the native files I tried just about anything & couldn't get it to work. Would it be possible for you to provide a barebones project that is already linked? Thanks for the sticker lib, good stuff

**Comment by Jobeso** [comment]
I want to include a sample project which also should make the testing for PRs easier. I can't tell you when I find time to finish this though. This would also require to change the project structure a bit.

**Comment by Jobeso** [comment]
@creeptosis Created a sample project. You can check it out [here](https://github.com/Jobeso/react-native-whatsapp-stickers/tree/master/example). Hope it helps you finding the problem. 
When creating the example project I also needed to bump the `minSdkVersion`. After that android worked fine. 
For iOS i noticed I needed to apply the solution from [this issue](https://github.com/Jobeso/react-native-whatsapp-stickers/issues/16#issuecomment-468883862) and also added it to the readme [here](https://github.com/Jobeso/react-native-whatsapp-stickers/blob/master/README.md#integrate-webp-framework). However, I didn't need to do this in another app that uses this package in production.
I also needed to apply the solution from #18 which I now added to troubleshooting in the readme. Maybe it helps you, too.

**Comment by Jobeso** [comment]
v2.0.0 was just released which adds RN 0.60 support. Please reopen the issue if your problem still persists.
