### ISSUE TITLE
 Could not find auto-linked libraries (swift)

### ISSUE THREAD

**Issue by pandanr1** [Jobeso/react-native-whatsapp-stickers#18]
## Environment
iOs

## Describtion
If you got an error when building your ios/xcode project like this: 

ld: warning: Could not find auto-linked library 'swiftFoundation'...

## Solution

xCode -> Click File -> new File -> notused.swift -> Click yes when it asks for creating bridge-headers...

**Comment by Jobeso** [comment]
Thanks for this contribution. I added a troubleshooting section to the readme with this hint.
