### ISSUE TITLE
Does iOS need .png or .webp

### ISSUE THREAD

**Issue by pandanr1** [Jobeso/react-native-whatsapp-stickers#19]
## Environment
iOS

## Describtion
Crashes when sending stickers to whatsapp

## Reproducible Demo
Does iOS need .png or .webp? .png is used in examples but does it make sense?

**Comment by Jobeso** [comment]
On iOS you need to use png values. Yes, that means you have two times the same images, one in webp and one in png. I am aware that this is not optimal, I was running into errors as well when trying to use webp on iOS with the WhatsAppStickers SDK.

**Comment by pandanr1** [comment]
I added a folder image/ to xcode. The image folder contains a stickerpack1/ folder with the stickers in png. The tray_icon.png also lives in /images so the structure is like this:

``
images/
images/tray_icon.png
images/stickerpack1/
images/stickerpack1/sticker1.png
images/stickerpack1/sticker2.png
images/stickerpack1/sticker3.png
``

the app keeps crashing. So my question is - should i use for example the path: images/stickerpack1/sticker1.png in the config object or just: sticker1.png

Thx

**Comment by Jobeso** [comment]
I gather my stickers in a folder in the root project. Then I reference my stickers directly in the method.
```javascript
RNWhatsAppStickers.addSticker('sticker1.png', [ '👍' ])
```
