### ISSUE TITLE
update for android

### ISSUE THREAD

**Issue by Q8hma** [Jobeso/react-native-whatsapp-stickers#2]
hello
thanks for this and im asking when it will be available in android ?
thanks and best regard

**Comment by Jobeso** [comment]
Hey @Q8hma,
currently working on it. Can't tell you when it will be done. The android part is working completely different that iOS so I need to figure out a good way for a common react-native api to use.

**Comment by chbaluch** [comment]
Is the iOS working?

**Comment by Jobeso** [comment]
@Q8hma First android support is in master. The common api is not that great yet but everything works. I will publish a new release probably today.

@chbaluch yes, iOS is working

**Comment by Jobeso** [comment]
version 1.1.0 with android support is now live
