### ISSUE TITLE
Gradle bug on build

### ISSUE THREAD

**Issue by yojik94** [Jobeso/react-native-whatsapp-stickers#29]
Hi, after install this package on build I see error 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0." , and "error Failed to install the app". How I can solve this problem?
![image](https://user-images.githubusercontent.com/37308889/62131343-ae1d8000-b2e3-11e9-9364-f2b916c9db7a.png)

**Comment by Jobeso** [comment]
v2.0.0 was just released which adds RN 0.60 support. Please reopen the issue if your problem still persists.
