### ISSUE TITLE
iOS error in method sendToWhatsApp

### ISSUE THREAD

**Issue by yoandypv** [Jobeso/react-native-whatsapp-stickers#3]
He, in file StickerPack.swift, method sendToWhatsap (line 183), the specific line self.trayImage.image!.pngData()?.base64EncodingString() say the following error: UIImage has no member 'pngData'

I 'm using XCode 9.

Cheers,

**Comment by Jobeso** [comment]
Hey @yoandypv,
can you try to open the [example app](https://github.com/WhatsApp/stickers) from WhatsApp and see if you can compile this. I am suggesting this to see if this is a XCode 9 problem. The `StickerPack.swift` file is one of the files written by the WhatsApp Team.

**Comment by Jobeso** [comment]
closing this for now due to inactivity. Feel free to reopen it any time.

**Comment by digiperfect-janak** [comment]
I encountered this error when the image we were trying to read was WebP and not PNG  OR the file path was wrong.
