### ISSUE TITLE
Unable to open app

### ISSUE THREAD

**Issue by iamkatta** [Jobeso/react-native-whatsapp-stickers#36]
Hello,

I have added the package to my project and in build the project, build installed the app in the emulator, but where ever i try to open the app its throwing the error with the message "app is stopped".

I need the help.

Thanks

**Comment by Jobeso** [comment]
v2.0.0 was just released which adds RN 0.60 support. Please reopen the issue if your problem still persists.

**Comment by iamkatta** [comment]
Hello,
I have installed the new version but got the same response.
