### ISSUE TITLE
Xcode app validation errors 

### ISSUE THREAD

**Issue by hszeto** [Jobeso/react-native-whatsapp-stickers#47]
## Environment
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 113.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.13.0
    react-native-cli: 2.0.1

## Description
I'm trying to deploy to App store. When Validating the app (under Window>Organizer), I kept getting the following errors:

```
Distribution failed with errors:

App Store Connect Operation Error
Invalid Image Path - No image found at the path referenced under key
'CFBundleIcons': 'AppIcon1024x1024'

App Store Connect Operation Error
Missing required icon file. The bundle does not contain an app icon for
iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS
versions >= 7.0.

App Store Connect Operation Error
Invalid App Store Icon. The App Store Icon in the asset catalog in
'MyCoolWhatsAppStickers.app' can't be transparent nor contain an alpha channel.
```

I generated the icon set at `https://makeappicon.com` and copy&paste the `AppIcon.appiconset` folder in `Images.xcassets`

What am I missing?

**Comment by hszeto** [comment]
hmmm... anyone?

**Comment by Jobeso** [comment]
> Missing required icon file. The bundle does not contain an app icon for
> iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS
> versions >= 7.0.

You don't have the 120x120. It is the easiest to do this via Xcode because you see the icons you are missing. Maybe this will help you.
[https://stackoverflow.com/questions/28170520/ios-how-to-set-app-icon-and-launch-images/45122603](https://stackoverflow.com/questions/28170520/ios-how-to-set-app-icon-and-launch-images/45122603)

As this error is not related to this library, I'll close the issue.
