### ISSUE TITLE
debug mode working fine..i get this error when i build release apk

### ISSUE THREAD

**Issue by kaneki666** [Jobeso/react-native-whatsapp-stickers#58]
Task :react-native-whatsapp-stickers:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-whatsapp-stickers:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\User\.gradle\caches\transforms-2\files-2.1\37631cd0ab1b46aeb23414622984ad25\appcompat-1.0.2\res\values-v26\values-v26.xml:5:5-8:13: AAPT: error: resource android:attr/colorError not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\37631cd0ab1b46aeb23414622984ad25\appcompat-1.0.2\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\37631cd0ab1b46aeb23414622984ad25\appcompat-1.0.2\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\37631cd0ab1b46aeb23414622984ad25\appcompat-1.0.2\res\values-v28\values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\37631cd0ab1b46aeb23414622984ad25\appcompat-1.0.2\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontStyle not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/font not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontWeight not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/startX not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/startY not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/endX not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/endY not found.

     C:\Users\User\.gradle\caches\transforms-2\files-2.1\1cd17b4a4c7e4b94a301254fec05bdc3\core-1.0.1\res\values\values.xml:126:5-132:25: AAPT: error: resource android:attr/offset not found.

**Comment by 2b-dev** [comment]
Sorry, this not about your issues,
I use React Native 0.63.4 and Install this package ( yarn add react-native-whatsapp-stickers )
but i can't open app ( npx react-native run-android )
can u help me ?

**Comment by kaneki666** [comment]
What error u get? Show it

**Comment by 2b-dev** [comment]
> What error u get? Show it

can't open app
// run and not open anything

**Comment by 2b-dev** [comment]
> > What error u get? Show it
> 
> can't open app
> // run and not open anything

Ok I know, I should create Assets, contents.json :)
